# Generated by Django 3.2.3 on 2021-06-16 01:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tipo',
            fields=[
                ('idTipoUsuario', models.IntegerField(primary_key=True, serialize=False, verbose_name='Id del usuario')),
                ('tipo', models.CharField(max_length=10, verbose_name='Tipo de usuario')),
            ],
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('rut', models.CharField(max_length=10, primary_key=True, serialize=False, verbose_name='Rut del usuario')),
                ('nombre', models.CharField(max_length=20, verbose_name='Nombre usuario')),
                ('apellido', models.CharField(max_length=20, verbose_name='Apellido usuario')),
                ('correo', models.EmailField(max_length=20, verbose_name='Correo electrónico')),
                ('contrasena', models.CharField(max_length=9, verbose_name='contraseña')),
                ('tipo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.tipo')),
            ],
        ),
    ]
