# Generated by Django 3.2.3 on 2021-06-16 01:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tipo',
            name='tipo',
            field=models.CharField(max_length=20, verbose_name='Tipo de usuario'),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='apellido',
            field=models.CharField(max_length=50, verbose_name='Apellido usuario'),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='correo',
            field=models.EmailField(max_length=50, verbose_name='Correo electrónico'),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='nombre',
            field=models.CharField(max_length=50, verbose_name='Nombre usuario'),
        ),
    ]
